app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', "Submission@create");
Route::post('/', "Submission@store");

Route::get('admin/expiring', 'Curate@expiring')->name('expiring');
Route::resource('admin', 'Curate');

Route::auth();

Route::get('/home', 'HomeController@index');

app/Submission.php
<?php

namespace App;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Submission extends Model implements HasMedia
{
    use HasMediaTrait;

    public function isExpiringSoon() {
        $notify_date = $this->created_at->addDays(80);
        $now = Carbon::now();
        return $now->gte($notify_date);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Curate.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Submission;
use Storage;
use Carbon\Carbon;

class Curate extends Controller
{
    public function index()
    {
        $submissions = Submission::all();
        return view('curate.index', compact('submissions'));
    }

    public function expiring()
    {
        $submissions = Submission::where('created_at', '<=', Carbon::now()->subDays(80))->get();
        return view('curate.index', compact('submissions'));
    }

    public function recent()
    {
    }

    public function show($id)
    {
        $submission = Submission::find($id);
        return view('curate.show', compact('submission'));
    }

    public function edit($id)
    {
        $submission = Submission::find($id);
        return view('curate.edit', compact('submission'));
    }

    public function update(Request $request, $id)
    {
    }

    public function destroy($id)
    {
        $submission = Submission::find($id);
        $submission->delete();
        return redirect()->route('admin.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Submission.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Submission;
use Storage;

class Submission extends Controller
{
    public function create()
    {
        return view('submissions.index');
    }

    public function store(Request $request)
    {
        $submission = new Submission();
        // agreement info
        $submission->on_air = $request->input('on_air');
        $submission->on_stream = $request->input('on_stream');
        $submission->on_facebook = $request->input('on_facebook');
        $submission->on_youtube = $request->input('on_youtube');

        // artist contact info
        $submission->first_name = $request->input('fname');
        $submission->last_name = $request->input('lname');
        $submission->email = $request->input('email');
        $submission->address = $request->input('mailing');

        // track infos
        $submission->track_artist = $request->input('track_artist');
        $submission->track_name = $request->input('track_name');
        $submission->track_length = $request->input('track_length');
        $submission->video_director = $request->input('track_director');
        $submission->record_label = $request->input('track_label');
        $submission->release_date = $request->input('release_preference');

        // have to save it before adding media to it
        $submission->save();
        $submission->addMediaFromRequest('upload')->toCollectionOnDisk('media', 's3');

        // Save once more with new associations
        $submission->save();

        // now need to trigger queue job for sending email

        return view('submissions.thanks');
    }
}

resources/views/curate/index.blade.php
@extends('curate.layout')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Submissions</div>
        <div class="panel-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Submitted On</th>
                        <th>Track Title</th>
                        <th>Artist / Label</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($submissions as $submission)
                    <tr class="{{$submission->isExpiringSoon() ? 'danger' : ''}}">
                        <th scope="row">{{$submission->id}}</th>
                        <td>{{$submission->created_at}}</td>
                        <td>{{$submission->track_name}}</td>
                        <td>{{$submission->first_name}} {{$submission->last_name}} / {{$submission->record_label}}</td>
                        <td>{{link_to_route('admin.show', 'View', ['id' => $submission->id], ['class' => 'btn btn-sm btn-primary'])}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div>
@endsection

resources/views/curate/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Adult Swim Music Video Submission - Admin</title>
</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1>Adult Swim Music Video Submission - Admin</h1>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <ul class="list-group">
                    <li class="list-group-item">{{ link_to_route('admin.index', 'All Submissions') }}</li>
                    <li class="list-group-item">{{ link_to_route('expiring', 'Expiring Soon') }}</li>
                </ul>
            </div>
        </div>

        <div class="col-md-8">
            @yield('content')
        </div>

    </div>
</body>
</html>

resources/views/curate/show.blade.php
@extends('curate.layout')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Submission</div>
        <div class="panel-body">
            <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="info">
                            <td></td>
                            <th scope="row">Submission Info</th>
                        </tr>

                        <tr>
                            <th scope="row">Submitted on</th>
                            <td>{{$submission->created_at}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Expires On</th>
                            <td>{{$submission->created_at->addDays(90)}}</td>
                        </tr>

                        <tr class="info">
                            <td></td>
                            <th scope="row">Artist Information</th>
                        </tr>

                        <tr>
                            <th scope="row">Artist Name</th>
                            <td>{{$submission->first_name}} {{$submission->last_name}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Artist Email</th>
                            <td>{{$submission->email}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Artist Address</th>
                            <td>{{$submission->address}}</td>
                        </tr>

                        <tr class="info">
                            <td></td>
                            <th scope="row">Track Information</th>
                        </tr>

                        <tr>
                            <th scope="row">Track URL</th>
                            @if($submission->hasMedia())
                                <td><a href="{{$submission->getMedia()[0]->getUrl()}}">{{$submission->getMedia()[0]->getUrl()}}</a></td>
                            @endif
                        </tr>

                        <tr>
                            <th scope="row">Track Name</th>
                            <td>{{$submission->track_name}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Track Length</th>
                            <td>{{$submission->track_length}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Video Director</th>
                            <td>{{$submission->video_director}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Record Label</th>
                            <td>{{$submission->record_label}}</td>
                        </tr>

                        <tr class="info">
                            <td></td>
                            <th scope="row">Release</th>
                        </tr>

                        <tr>
                            <th scope="row">On Air</th>
                            <td>{{$submission->on_air}}</td>
                        </tr>

                        <tr>
                            <th scope="row">On Stream</th>
                            <td>{{$submission->on_stream}}</td>
                        </tr>

                        <tr>
                            <th scope="row">On Facebook</th>
                            <td>{{$submission->on_facebook}}</td>
                        </tr>

                        <tr>
                            <th scope="row">On Youtube</th>
                            <td>{{$submission->on_youtube}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Preferred Release Date</th>
                            <td>{{$submission->release_date}}</td>
                        </tr>
                    </tbody>
            </table>
            {{ link_to_route('admin.index', 'Back', null, ['class' => 'btn btn-primary pull-left'] )}}

            {{ Form::open(['route' => ['admin.destroy', $submission->id], 'method' => 'delete']) }}
                {{ Form::submit('Delete', ['class' => 'btn btn-danger pull-right']) }}
            {{ Form::close() }}


        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/submissions/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8>
        <meta name=viewport content="width=device-width,initial-scale=1">
        <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
        <title>Adult Swim Music Video Submission</title>
        <link rel=stylesheet href="/css/main.css">
    </head>
    <body>

        <app></app>

        <script src="/js/main.js"></script>
    </body>
</html>

resources/views/submissions/thanks.blade.php
<h1>Thanks!</h1>